#
#FROM ubuntu:16.04
FROM postgres:9.6.1
#
ENV DJANGO_ENV dev
#ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
#
RUN apt-get update && apt-get install -y \
	python3 python3-pip apache2
#  postgresql-9.5
#
#COPY postgres/pg_hba.conf /etc/postgresql/9.5/main/pg_hba.conf 
#COPY postgres/postgresql.conf /etc/postgresql/9.5/main/postgresql.conf 
#RUN /bin/chown postgres:postgres /etc/postgresql/9.5/main/*
#
#RUN /usr/lib/postgresql/9.5/bin/postgres -D /var/lib/postgresql/data
#
WORKDIR /choral
#
RUN pip3 install --upgrade pip
#
ADD requirements.txt /choral
RUN pip3 install -r requirements.txt
#
COPY choral /choral/
#
EXPOSE 80
#
#
