# Generated by Django 2.1.2 on 2018-10-02 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=32)),
                ('disc_count', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('file_name', models.CharField(max_length=64)),
                ('format', models.CharField(max_length=16)),
                ('genre', models.CharField(max_length=16)),
                ('mb_id', models.CharField(max_length=64)),
                ('note', models.CharField(max_length=128)),
                ('release', models.DateField()),
                ('track_count', models.IntegerField()),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('mb_id', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disc', models.CharField(max_length=64)),
                ('duration', models.CharField(max_length=64)),
                ('file_name', models.CharField(max_length=64)),
                ('mb_id', models.CharField(max_length=64)),
                ('note', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('track', models.CharField(max_length=64)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.Album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.Artist')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.Artist'),
        ),
    ]
