# Generated by Django 2.1.2 on 2019-01-22 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_bogus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bogus',
        ),
    ]
